steps:
  # Print the current commit to debug
  - name: 'gcr.io/cloud-builders/git'
    args: ['rev-parse', 'HEAD']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nextjs18-cloud-run:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nextjs18-cloud-run:$COMMIT_SHA']

  # Also tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/nextjs18-cloud-run:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/nextjs18-cloud-run:latest']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/nextjs18-cloud-run:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'nextjs18-cloud-run'
      - '--image=gcr.io/$PROJECT_ID/nextjs18-cloud-run:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/nextjs18-cloud-run:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/nextjs18-cloud-run:latest'